"""Added emembedding to users table

Revision ID: 3cbe4df997bc
Revises: cec1df55819e
Create Date: 2025-04-05 12:22:31.581686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbe4df997bc'
down_revision: Union[str, None] = 'cec1df55819e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'embedding')
    # ### end Alembic commands ###
