"""empty message

Revision ID: cec1df55819e
Revises: 
Create Date: 2025-04-05 12:09:00.456054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec1df55819e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_card', sa.String(length=15), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.String(length=15), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('place_of_origin', sa.String(length=255), nullable=True),
    sa.Column('place_of_residence', sa.String(length=255), nullable=True),
    sa.Column('date_of_expiry', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
